<?php
/**
 * auto generated file by PHPExtensionStubGenerator
 */
const BITCOINCONSENSUS_ERR_OK = 0;
const BITCOINCONSENSUS_ERR_TX_INDEX = 1;
const BITCOINCONSENSUS_ERR_TX_SIZE_MISMATCH = 2;
const BITCOINCONSENSUS_ERR_TX_DESERIALIZE = 3;
const BITCOINCONSENSUS_ERR_AMOUNT_REQUIRED = 4;
const BITCOINCONSENSUS_ERR_INVALID_FLAGS = 5;
const BITCOINCONSENSUS_SCRIPT_FLAGS_VERIFY_NONE = 0;
const BITCOINCONSENSUS_SCRIPT_FLAGS_VERIFY_P2SH = 1;
const BITCOINCONSENSUS_SCRIPT_FLAGS_VERIFY_DERSIG = 4;
const BITCOINCONSENSUS_SCRIPT_FLAGS_VERIFY_CHECKLOCKTIMEVERIFY = 512;
const BITCOINCONSENSUS_SCRIPT_FLAGS_VERIFY_CHECKSEQUENCEVERIFY = 1024;
const BITCOINCONSENSUS_SCRIPT_FLAGS_VERIFY_WITNESS = 2048;
const BITCOINCONSENSUS_SCRIPT_FLAGS_VERIFY_NULLDUMMY = 16;
const BITCOINCONSENSUS_SCRIPT_FLAGS_VERIFY_ALL = 3605;
