<?php
/**
 * auto generated file by PHPExtensionStubGenerator
 */
const BITCOINCONSENSUS_SCRIPT_FLAGS_VERIFY_NONE = 0;
const BITCOINCONSENSUS_SCRIPT_FLAGS_VERIFY_P2SH = 1;
const BITCOINCONSENSUS_SCRIPT_FLAGS_VERIFY_DERSIG = 4;
const BITCOINCONSENSUS_SCRIPT_FLAGS_VERIFY_CHECKLOCKTIMEVERIFY = 512;
const BITCOINCONSENSUS_SCRIPT_FLAGS_VERIFY_CHECKSEQUENCEVERIFY = 1024;
const BITCOINCONSENSUS_SCRIPT_FLAGS_VERIFY_WITNESS = 2048;
const BITCOINCONSENSUS_VERIFY_NONE = 0;
const BITCOINCONSENSUS_VERIFY_P2SH = 1;
const BITCOINCONSENSUS_VERIFY_DERSIG = 4;
const BITCOINCONSENSUS_VERIFY_CHECKLOCKTIMEVERIFY = 512;
const BITCOINCONSENSUS_VERIFY_CHECKSEQUENCEVERIFY = 1024;
const BITCOINCONSENSUS_VERIFY_WITNESS = 2048;
const BITCOINCONSENSUS_VERIFY_ALL = 3589;
